### ISSUE TITLE
Tìm hiểu SketchUp

### ISSUE THREAD

**Issue by LongNg89** [LongNg89/SE08.Group22.1#13]
# SketchUp Woodworking Tutorial
### Phần 1
- Điều hướng xung quanh trong mô hình
- Tạo các hình khối cơ bản bằng `rectangle` và `line` tools
- Sử dụng `push` `pull` tool để tạo khối 3D

**Comment by DamQuynhGiang157** [comment]
### CÁCH SỬ DỤNG SKETCHUP CƠ BẢN.
**Sketchup là gì?**
![image](https://user-images.githubusercontent.com/91444726/150108589-a0491f07-a00f-47d5-87ae-02e768365998.png)
Sketchup là một phần mềm vẽ 3d của Google, nó khá dễ sữ dụng nên có thể tự học được, nhất là những ai đã biết qua Autocad hoặc các chương trình 3d khác. Cách nó thao tác trên hình vẽ và hiệu chỉnh khá giống Autocad nên tốc độ vẽ nhanh giống như tên gọi của nó là vẽ sketch (phác thảo). Ngay cả phần Layout nó cũng giống như bên Autocad mặc dù chưa hoàn chỉnh lắm. Ngoài ra cùng với sự hỗ trợ của Vray nên việc render kết xuất hình ảnh của nó giống như vẽ bên 3dsmax.


**Làm quen với giao diện của Sketchup**
![image](https://user-images.githubusercontent.com/91444726/150113852-2daf0c35-944d-42ab-9d7a-d437649561fb.png)

- Mục số 01 : Thanh trình đơn menu, chức năng của từng chuyên mục thì mình sẽ có bài hướng dẫn trong những buổi tiếp theo. 
- Mục số 02 : Các công cụ vẽ cơ bản trong Sketchup. 
- Mục số 03 : Các công cụ hiệu chỉnh cơ bản trong Sketchup. 
- Mục số 04 : Các công cụ ghi kích thước, chữ ghi chú, tô vật liệu và điều khiển vùng nhìn trong Sketchup. 
- Mục số 05 : Các công cụ kết nối thư viện và plugins trong Sketchup. 
- Mục số 07 : Vùng không gian vẽ. 
- Mục số 08 : Biểu tượng con người, mỗi version Sketchup đều có hình người khác nhau. 
- Mục số 09 : Góc toạ độ UCS, màu đỏ tượng trưng cho trục X, màu xanh lá tượng trưng cho trục Y và màu xanh dương tượng trưng cho trục Z.  
- Mục số 10 : Bảng điều khiển là nơi tập trung các công cụ quản lý đối tượng trong Sketchup. 
- Mục số 11 : Thông tin địa lý và biểu phí của mô hình Sketchup . 
- Mục số 12 : Thông tin các phím tắt chức năng bổ sung cho công cụ chính. 
- Mục số 13 : Hiển thị thông số kích thước nhập vào giống như dòng lệnh của Autocad.


**Các công cụ vẽ trong Sketchup**

> Khi lần đầu tiên mới mở Sketchup các bạn nhớ bấm vào mục Templates chọn Architectural Drawing hệ Millimeter, vì đây là template hệ mét phù hợp với hệ đơn vị tiêu chuẩn của Việt Nam.

![image](https://user-images.githubusercontent.com/91444726/150115492-2bef8ce2-55ba-4a58-827e-493373727b07.png)

1. Công cụ SELECT - Chọn đối tượng
- Phím tắt : thanh Space Bar trên bàn phím. 
- Công dụng : Dùng để chọn các đối tượng để sửa đổi khi sử dụng các công cụ hoặc lệnh khác. 
- Cách thức hoạt động : Nhấp vào một đối tượng bằng cách bấm chuột trái 1 lần hoặc rê chuột để chọn nhiều đối tượng cùng 1 lúc. Rê chuột từ trái qua phải là chọn kiểu window, các đối tượng nào nằm lọt trong vùng chọn thì mới được chọn, rê chuột từ phải sang trái là chọn kiểu crossing, các đối tượng nào nằm trong vùng chọn và bị đường bao của vùng chọn cắt qua thì những đối tượng đó sẽ được chọn hết. Điều này giống như cách thức chọn trong Autocad. 
- Các phím hỗ trợ thêm : 
• Ctrl = Thêm một đối tượng vào tập hợp các đối tượng đã chọn. 
• Shift + Ctrl = Trừ một đối tượng khỏi tập hợp các đối tượng đã chọn. 
• Shift = Nếu đối tượng có nằm trong tập hợp các đối tượng đã chọn thì khi bấm vào nó sẽ trừ ra, còn đối tượng không nằm trong tập hợp các đối tượng đã chọn thì khi bấm nó sẽ cộng vào tập hợp đó. 
• Ctrl + A = Chọn tất cả các đối tượng hiển thị trong mô hình.
2. Công cụ ERASE - Xóa đối tượng
![image](https://user-images.githubusercontent.com/91444726/150117020-5c159b0e-889d-4d3f-9119-431ba6a0ad8f.png)
- Phím tắt : E hoặc Delete 
- Công dụng : Xóa các đối tượng. 
- Cách thức hoạt động : Nhấp vào đối tượng để xóa. Ngoài ra nếu ta giữ nút chuột kéo qua các đối tượng thì tất cả các đối tượng sẽ bị xóa khi thả nút chuột ra. 
- Các phím hỗ trợ thêm : 
• Shift = Ẩn các đối tượng. 
• Ctrl = Làm mềm và làm mịn các đối tượng. 
• Shift + Ctrl = Làm đối tượng không mềm và không trơn tru. 
• Alt = Bỏ chọn các thực thể được chọn bởi công cụ Eraser.
3. Công cụ LINE - Vẽ đường thẳng
![image](https://user-images.githubusercontent.com/91444726/150117394-cfafd60a-d2af-469c-84a1-df61a289c89d.png)
- Phím tắt : L
- Công dụng : Vẽ các cạnh hoặc các Đường thẳng. 
- Cách thức hoạt động : Nhấp vào điểm bắt đầu. Di chuyển con trỏ. Nhấp vào điểm kết thúc. Di chuyển tiếp con trỏ. Nhấp để tạo đường kết nối. Lặp lại bước 4 để tạo các đường được kết nối hoặc quay lại điểm bắt đầu của điểm đầu tiên để tạo bề mặt. 
- Các phím hỗ trợ thêm : 
• Shift = Khóa đường vẽ kế tiếp theo hướng mong muốn.
• Các phím mũi tên = Khóa dòng theo hướng suy luận cụ thể (khoá hướng lên xuống = trục màu xanh lam, khoá hướng trước sau = trục màu xanh lục và khoá hướng trái phải = trục màu đỏ).
4. Công cụ FREEHAND - Vẽ phác thảo bằng tay
![image](https://user-images.githubusercontent.com/91444726/150117778-de0e3f13-2f75-4c7e-8a83-d47fd13aa58e.png)
- Phím tắt : không có 
- Công dụng : Vẽ đường tự do giống nét vẽ tay hoặc vẽ đối tượng dạng 3D Polyline giống như Autocad. 
- Cách thức hoạt động : Nhấp và giữ tại điểm bắt đầu của đường cong. Kéo con trỏ để vẽ. Nhả nút chuột để dừng. Đường cong kết thúc tại điểm bắt đầu để vẽ hình dạng khép kín. Esc = Hủy thao tác. 
- Các phím hỗ trợ thêm : 
• Shift = Vẽ đối tượng Polyline 3D
5. Công cụ ARC - Vẽ đường cong
![image](https://user-images.githubusercontent.com/91444726/150118493-0d375f55-8fb5-4eb0-a8bc-acd1ac8e2b1b.png)
- Phím tắt : A 
- Công dụng : Vẽ đường cong. 
- Cách thức hoạt động : Nhấp để xác định tâm của cung tròn. Theo tùy chọn, nhấp và kéo điểm đầu tiên để thiết lập mặt phẳng vẽ. Di chuyển con trỏ để xác định điểm cung đầu tiên hoặc nhập bán kính. Nhấp để thiết lập điểm cung đầu tiên. Di chuyển con trỏ xung quanh hướng dẫn thước đo góc hoặc nhập góc. Nhấp để đặt điểm cung thứ hai. Esc = Hủy thao tác. 
> Mẹo: Nhấp vào Window> Model Info> Units> Angle Units để thay đổi góc chụp. 
- Các phím hỗ trợ thêm : 
• Ctrl '+' hoặc Ctrl '-' = Thay đổi số lượng phân đoạn đường cong. 
• Giữ phím Shift = Khóa các hướng vẽ. 
• Các phím mũi tên (trước lần nhấp đầu tiên) = Khóa hướng trục quay của thước đo góc (Lên xuống = Xanh lam, Trước sau = Xanh lục, Phải trái = Đỏ). 
• Các phím mũi tên (sau lần nhấp đầu tiên) = Khóa hướng vẽ theo hướng suy luận cụ thể (Lên xuống = Xanh lam, Trước sau = Lục, Phải trái = Đỏ)
6. Công cụ vẽ đường cong qua 2 điểm
![image](https://user-images.githubusercontent.com/91444726/150119047-14f96e0b-58de-4fcb-b428-8194452cbe2d.png)
- Phím tắt : không có 
- Công dụng : Vẽ đường cong qua 2 điểm. 
- Cách thức hoạt động : Nhấp để thiết lập điểm bắt đầu của cung tròn. Di chuyển con trỏ. Nhấp vào điểm kết thúc của cung tròn hoặc nhập giá trị. Di chuyển con trỏ vuông góc với dòng để đặt khoảng cách phình ra hoặc nhập giá trị. Nhấp để kết thúc lệnh. Esc = Hủy thao tác. 
- Các phím hỗ trợ thêm : 
• Ctrl '+' hoặc Ctrl '-' = Thay đổi số lượng phân đoạn đường cong. 
• Shift = Khóa công cụ theo hướng suy luận hiện tại 
• Các phím mũi tên = Khóa hướng vẽ theo hướng suy luận cụ thể (Lên xuống = Xanh lam, Trước sau = Xanh lục, Phải trái = Đỏ).
7. Công cụ vẽ đường cong qua 3 điểm
![image](https://user-images.githubusercontent.com/91444726/150119378-b035f0f2-8cf4-4f9c-8523-7d36632ef291.png)
- Phím tắt : không có 
- Công dụng : Vẽ đường cong qua 3 điểm. 
- Cách thức hoạt động : Nhấp để thiết lập điểm bắt đầu của cung tròn. Di chuyển con trỏ ra khỏi điểm bắt đầu. Nhấp để đặt điểm thứ hai. Cung sẽ luôn đi qua điểm này. Di chuyển con trỏ đến điểm cuối. Một góc sẽ xuất hiện trong hộp đo lường ở dòng tình trạng và bạn có thể nhập một giá trị chính xác. Nhấp để kết thúc lệnh. Esc = Hủy thao tác. 
- Các phím hỗ trợ thêm : 
• Ctrl '+' hoặc Ctrl '-' = Thay đổi số lượng phân đoạn đường cong. 
• Shift = Khóa công cụ theo hướng suy luận hiện tại cho bất kỳ điểm nào. 
• Các phím mũi tên = Khóa hướng vẽ theo hướng suy luận cụ thể (Lên xuống = Xanh lam, Trước sau = Xanh lục, Phải trái = Đỏ).
8. Công cụ PIE - Vẽ một phần mặt phẳng hình tròn
![image](https://user-images.githubusercontent.com/91444726/150119653-d6c1978d-2656-4269-ad4b-50c6f6f42614.png)
- Phím tắt : không có 
- Công dụng : Vẽ mặt phẳng tròn bị cắt giống như ổ bánh bông lan tròn bị cắt khoanh. 
- Cách thức hoạt động : Nhấp để xác định tâm của chiếc bánh. Theo tùy chọn, nhấp và kéo điểm đầu tiên để thiết lập mặt phẳng vẽ. Di chuyển con trỏ để xác định điểm cung đầu tiên hoặc nhập bán kính. Nhấp để thiết lập điểm cung đầu tiên. Di chuyển con trỏ xung quanh hướng dẫn thước đo góc hoặc nhập góc. Nhấp để đặt điểm cung thứ hai. Esc = Hủy thao tác. * Mẹo: Nhấp vào Window> Model Info> Units> Angle Units để thay đổi góc chụp. 
- Các phím hỗ trợ thêm : 
• Ctrl '+' hoặc Ctrl '-' = Thay đổi số lượng phân đoạn 
• Giữ phím Shift = Khóa các hướng theo mong muốn. • Các phím mũi tên (trước lần nhấp đầu tiên) = Khóa hướng trục quay của thước đo góc (Lên xuống = Xanh lam, Trước sau = Xanh lục, Phải trái = Đỏ). 
• Các phím mũi tên (sau lần nhấp đầu tiên) = Khóa hướng vẽ theo hướng suy luận cụ thể (Lên xuống = Xanh lam, Trước sau = Xanh lục, Phải trái = Đỏ).

> Video tham khảo: https://youtu.be/r517py6ttPY

**Comment by Nguyenthithaotrang** [comment]
# **Phần 2**
I.Tạo đường vòng cung
Sử dụng Drawing Tools
Arc Tool (cung tròn)
Kích hoạt công cụ -> nhập độ trơn đường cong nếu muốn (mặc định là 12)  -> click chọn điểm đầu cung -> kéo và click chọn điểm cuối cung -> kéo và click đoạn trung trực dây cung
<img width="164" alt="image" src="https://user-images.githubusercontent.com/90678425/150562995-5c272c8e-bccc-467d-9a12-575a30bd47e8.png">

II.Tổ chức mô hình với components và groups
SỰ KHÁC NHAU GIỮA GROUP VÀ COMPONENT TRONG SKETCHUP 

- Group là nhóm các đối tượng lại với nhau, đối tượng được nhóm có thể là segment, face hoặc nhiều đối tượng gộp chung với nhau. Khi sao chép ra thì group nào sẽ độc lập group đó.
- Component cũng là nhóm các đối tượng như group nhưng cho phép đăt tên và mô tả, khi component nào mà thay đổi thì các component khác mà được sao chép ra sẽ ảnh hưởng theo. Việc này giống như lệnh Block ở bên Autocad.

Component:  điều khiển hiển thị của các group, components trong không gian vẽ.
Thang trượt **Fade simllar component** chỉnh độ mờ của các bản sao còn lại khi mở bối cảnh của chúng. Có thể check mục Hide để ẩn các bản sao còn lại
Thang trượt **Fade resf of model** chỉnh độ mở của phần mô hình còn lại khi mở bối cảnh của 1 group, component. Có thể check mục Hide để ẩn các mô hình còn lại
Có thể check Show component axes để hiển thị trục của mỗi group, component

1.Component Browser (Quản ly Component)
Bật tắt hộp thoại qua menu **Window/Components**. Thông qua hộp thoại, sử dụng các phím mũi tên, danh sách các library để tìm kiếm các component.
Để chèn một component vào mộ hình, đơn giản click hiện hành component trong hộp thoại browser sau đó click lên vùng vẽ.
Để tạo một component: chọn các đối tượng cần tạo, click phải chọn **Make Component**. Sau đó đặt tên cho component. Tất cả các component dùng trong mô hình được hiển thị trong thư viện “In Model".
<img width="125" alt="image" src="https://user-images.githubusercontent.com/90678425/150563338-9b0c81e8-f3ce-4916-966f-31d82a1a962c.png">
_Khi import 1 mô hình SketchUp khác vào mô hình hiện hành nó sẽ tạo thành 1 component tương ứng._

**Menu động khi click phải lên một component trong mô hình:**

- **Entities Info** hiển thị và hiệu chỉnh các thuộc tính như: tên, mô tả thành phần hình học, số bản sao, layer chứa nó, thuộc tính tự động dán mặt, luôn quay về camera ...
- **Erase** để xóa component trong mô hình.**Hide** để tắt hiện thị component. **Lock** dùng để khóa component, tránh tác động vô ý.
- **Edit Component** để cô lập, đồng thời chuyển vào bối cảnh tương ứng để hiệu chinh component. Việc hiệu chinh đương nhiên ảnh hưởng tất cả các bản sao trong mô hình, trừ khi trước đó đã chọn Make Unique để tách component khỏi sự ràng buộc với các bản sao khác (tạo thành 1 compo nent mới).
<img width="135" alt="image" src="https://user-images.githubusercontent.com/90678425/150563624-f31c5b75-80f8-4aeb-8d0a-660242a9445f.png">

- **Explode** để phá vỡ component thành các đối tượng rời.
- **Unglue** dùng để hủy thuộc tính tự động dán mặt.
- **Reload** cập nhật lại các thay đổi của file gốc vào component hiện tại. Kết hợp với thủ thuật import một mô hình vào mô hình khác ta có hiệu ứng tương tự xref.
- **Save As** lưu component đang chọn thành file riêng.
- **Change Axes** thay đổi điểm chèn của một component. Sau khi thay đổi các component trong thư viện “In Model" sẽ mang điểm chèn mới (component trong các thư viện khác không ảnh hưởng).
- **Reset Scale/Reset Skew** khôi phục lại tỉ lệ, hình dáng gốc của componetn khi thu phóng hay biến dạng một component bên ngoài bối cảnh của nó (không thông qua lệnh Edit Component).
- **Scale Definition** cập nhật tỉ lệ mới của một component vào định nghĩa component. Sau khi cập nhật, các component đã chèn trước đó không thay đổi tỉ lệ nhưng các component từ lúc đó trở về sau khi chèn vào mô hình sẽ mang tỉ lệ mới.
- **Intersect with Model** thực hiện giao cắt component.
- **Flip Along** lật component theo các trục của nó.
- **Zoom Extents** phóng khít component lên khung nhìn.

**Menu động khi click phải lên component trong browser:**

- **Properties** dùng hiển thị và chỉnh một số thuộc tính tương tự như Entities Info, ngoại trừ Properties các tính năng có thêm như: bật tắt tính năng Expand để thống kê thành phần hình học có tính tới Componeth con hay không, nguồn load component ...
- **Delete** xóa component khỏi thư viện In Model cùng với tất cả các bản sao tương ứng trong mô hình.
- **Reload** cập nhật thay đổi file nguồn vào component trong thư viện cũng như bản sao tương ứng trong mô hình.
- **Save As** lưu thành file riêng
- **Select Instances** chọn tất cả các bản sao tương ứng trong mô hình.
- **Replace Selected** thay thế component đã chọn trước đó trong mô hình bằng component đang chọn trong thư viện.
<img width="134" alt="image" src="https://user-images.githubusercontent.com/90678425/150564172-f8a98bae-b77a-4500-8b51-ded740662958.png">

**Click vào nút hình tam giác tô đen nằm ngang, góc trên bên phải hộp thoại để kích hoạt Details Menu với các tính năng:**

- **Icon View/List View** duyệt component theo tên hay icon.
- **Refresh** cập nhật component khi có thay đổi trong hệ thống.
- **Purge Unused** xóa scomponent thừa trong mô hình.
- ****Add to / Remove** from Favorites** tạo hay xóa các thư viện component cá nhân.
<img width="248" alt="image" src="https://user-images.githubusercontent.com/90678425/150564338-c9dde4ae-034d-45de-8ce7-17d55d0afe41.png">

**2.Component Outliner (Quản lí Outliner)**
Bật tắt hộp thoại qua menu **Window/Outliner.** Chức năng chính của Component Outliner là quản lý theo cấu trúc phả hệ (hierarchical tree) các group_component trong mô hình, rất hữu ích khi phải làm việc với 1 mô hình lớn và phức tạp.
Trong hộp thoại, click tên group_Component để chọn, click đúp để mở bối cảnh tương ứng. Các thao tác khác có thể thực hiện thông qua menu động tương tự ngoài không gian vẽ.
Với group_component có cấp độ con, dùng kí hiệu (+) hay (-) trước nó để thả hay cuộn từng nhánh phả hệ. Chọn Expand All hay Collapse All trong Details Menu để thả hay cuộn toàn bộ phả hệ.
Có thể nhận dạng trạng thái mỗi group_component theo hệ thống kí hiệu hình chữ sau (xuất hiện đầu mỗi nhánh phả hệ)
<img width="306" alt="image" src="https://user-images.githubusercontent.com/90678425/150564422-28862dda-721c-4363-b323-e8a3304f9e81.png">


Có thể cấu trúc lại các group_component trong phả hệ bằng cách xác định vị trí nguồn, vị trí, dùng chuột thao tác kéo thả.

Có thể dùng bộ lọc các kí tự có trọng tên group_component bằng cách gõ kí tự vào ô Filter đầu hộp thoại.
_Cần phân biệt 2 loại: Instance name và Definition name. Các bản sao cùng loại trong mô hình cùng chia sẻ một định nghĩa chung. Vì thế, các group_component cùng loại có thể mang nhiều instance name giống hoặc khác nhau nhưng chỉ có duy nhất 1 definition name._
Instance name đứng đầu nhánh phả hệ còn Definition name nằm trong dấu ngoặc nhọn.
Sửa đổi instance name của group_component bằng cách chọn mục Rename trong menu động. Sửa đổi definition name thông qua mục Entity Info trong menu động.
Đầu tư cho việc đặt instance name, definition name cũng quản lí cấu trúc phả hệ group_component ngay từ đầu mang lại hiệu quả rất lớn trong việc cập nhật mô hình sau này.


**III.Sử dụng Move Tools**
<img width="278" alt="image" src="https://user-images.githubusercontent.com/90678425/150564543-84458ddd-4748-4c57-a84d-1a69002e6354.png">

Lệnh Move là tập hợp tổng hợp cùa các lệnh Move ( di chuyển ), Copy ( sao chép) , Stretch ( kéo dãn), Array ( sao chép theo thuộc tính) . Phím tắt là ( M)
1. Lệnh Move ( di chuyển) : chọn vật thể cần di chuyển sao đó chọn lệnh Move và sau đó chọn điểm thứ 1 và điểm thứ 2 trên hướng cần di chuyển.
   
<img width="173" alt="image" src="https://user-images.githubusercontent.com/90678425/150564558-db5d737d-ee6d-471c-b4f7-f8b079c428e6.png">
<img width="220" alt="image" src="https://user-images.githubusercontent.com/90678425/150564592-02e3892d-c9ad-4927-bb06-f64352c61fe5.png">

2.Lệnh Copy ( sao chép ) : chọn vật thể cần copy sau đó chọn lệnh Move và bấm Ctrl sau đó bấm lên xác định điểm thứ 1 và điểm thứ 2 trên hướng cần Sao chép.
  
<img width="188" alt="image" src="https://user-images.githubusercontent.com/90678425/150564620-69e8d94d-0a96-4eb5-a090-f0d69f547a31.png">
<img width="193" alt="image" src="https://user-images.githubusercontent.com/90678425/150564648-e7889f54-38db-4d22-a787-f60c4d03abc8.png">

3.Lệnh Array ( sao chép theo thuộc tính) : chọn vật thể cần copy sau đó chọn lệnh Move và bấm Ctrl sau đó bấm lên xác định điểm thứ 1 và điểm thứ 2 trên hướng cần Sao chép. Sao đó gõ Ax số đối tượng cần sao chép ví dụ 5 đối tượng thì gõ 5x, 10x..... Hoặc di chuyển đối tượng đến điểm cuối rồi gõ /A trong đó A là số khoảng cần chia.
<img width="385" alt="image" src="https://user-images.githubusercontent.com/90678425/150564678-0a8649df-0196-45be-a30a-0829041b37e4.png">

4.Lệnh Stretch ( kéo dãn): chọn mặt hoặc cạnhvật thể cần kéo dãn sao đó bấm lệnh Move , bấm lên xác định điểm thứ 1 và điểm thứ 2 trên hướng cần kéo dãn
<img width="416" alt="image" src="https://user-images.githubusercontent.com/90678425/150564704-a59ae3ef-acfa-420d-b420-a9538a1bb700.png">
