### ISSUE TITLE
Tuần 4: Bài tập

### ISSUE THREAD

**Issue by LongNg89** [LongNg89/SE08.Group22.1#7]
~~### Tạo G-code gia công tấm có thiết kế như sau:~~
~~- Kích thước tấm ABCD: 300x150cm~~
~~- Kích thước rãnh EFGH: 6x240cm~~
~~- Kích thước rãnh QRST: 4x60cm~~
~~- Đường kính lỗ O: 10cm~~
~~- Đường kính lỗ J, L: 14cm~~
~~- Đường kính lỗ M: 18cm~~

> ~~Removed~~
> ![Opera Snapshot_2021-11-14_232903_www geogebra org](https://user-images.githubusercontent.com/89681261/141690211-8a0c2abf-5a2b-4c97-859e-17fb0db8ba6d.png)

**Comment by Nguyenthithaotrang** [comment]
%
O1002
(-- GIA CONG TAM --)
G00 G17 G21 G40 G49 G80 G90
G91 G28 Z0.
(-- DAO PHAY 6MM--)
T1 M06
G00 G17 G90 G54 X0 Y0 S3650 M03
G43 H1 Z0 M08
(-- START MOTION --)
G0 X497. Y497. Z50.
G1 Z-15 F300
G1 X497. Y497.
G1 X497. Y2003.
G1 X1503. Y2003.
G1 X1503. Y497.
G1 X497. Y497.
G98 Z50.0
G0 X1303. Y753. Z50.
G1 Z-6 F300
G1 X1303. Y753.0
G1 X1347. Y753.
G1 X1347. Y1747.
G1 X1303. Y1747.
G1 X1303. Y753.0
G98 Z50.0
G0 X588. Y600. Z50.
G1 Z-15 F300
G2 I12 F350
G1 Z50
G0 X953. Y1500. Z50.
G1 Z-15 F300
G2 I47. F350
G1 Z50
G0 X588. Y1900. Z50.
G1 Z-15 F300
G2 I12 F350
G1 Z50
(-- END MOTION --)
M09
M05
G91 G28 Z0.
G28 X0. Y0.
G90
M30
%
